version: "3"

vars:
  DATABASE_URL: "postgres://postgres:foobarbaz@localhost:5432/postgres"
  IMAGE_REPO: vladyslavyarko/devops-directive-docker-course-api-node
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/node/api-node

includes:
  utils:
    taskfile: ../../../utils/Taskfile.yaml
    dir: ../../../utils

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: install dependencies
    cmds:
      - npm install

  install-ci:
    desc: install/download package dependencies
    cmds:
      - npm ci

  run:
    desc: Start node api
    cmds:
      - DATABASE_URL={{.DATABASE_URL}} npm run dev

  test:
    desc: run tests
    cmds:
      - npm run test
